### PR TITLE
build: add proto build system

### LINKED ISSUE #90: Add a proto build system
Cudos was built with starport and will need its own proto build system

### PR DESCRIPTION
**Pull request by catconcat**
This pull request introduces a new protobuf build system and fixes existing formatting/linting errors of protobuf files. 

Closes https://github.com/CudoVentures/cudos-node/issues/90

## Change

+ Add protobuf formatting, linting and generation command
+ Fix linting errors

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
Proto build working:

Screenshot 2023-12-18 at 11 53 01

A note on ghcr.io access denied:
1. Create access token in profile developer settings for docker download
2. `echo "$ACCESS_TOKEN" | docker login ghcr.io -u USERNAME --password-stdin`

More information on: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by catconcat** [comment]
It seems that the failing tests are related to the unused modules(nft, marketplace and addressbook), and not related to the proto build process. 
image

**Comment by nghuyenthevinh2000** [comment]
@nbaum @jgtormo I have reviewed this pr, can you have a look and merge it? Any questions related to how to re - run the proto build scripts and ci failing should be helpful

**Comment by nghuyenthevinh2000** [comment]
@tropicaldog please set this to ready

**Comment by jgtormo** [comment]
should we remove the nft, marketplace and addressbook modules before we merge this one in, to avoid failing tests?

**Comment by nghuyenthevinh2000** [comment]
> should we remove the nft, marketplace and addressbook modules before we merge this one in, to avoid failing tests?

yes, let's just keep this pr here until nft, marketplace, and addrbook modules removed. @tropicaldog can you create another pr for this issue: https://github.com/CudoVentures/cudos-node/issues/97

**Comment by nghuyenthevinh2000** [comment]
@jgtormo please review and merge this one

**Comment by tropicaldog** [comment]
Draft to add support for linting group module, added to cudos-node from [CudoVentures/cosmos-sdk](https://github.com/CudoVentures/cosmos-sdk), in reference to notional-labs/cudos-node#1

>4.  Remove x/group. TODO: need add group module

**Comment by tropicaldog** [comment]
After some discussion, it seems that this PR doesn't support format and linting v0.45.x version of cosmos-sdk, so I will close this PR now.

**Comment by tropicaldog** [comment]
Reopen

**Comment by catconcat** [comment]
>  ~~After some discussion, it seems that this PR doesn't support format and linting v0.45.x version of cosmos-sdk, so I will close this PR now.~~

This proto build system just doesn't work well with the `x/group` added directly to the cudos-node(as part of unforking process).

@jgtormo please confirm if we can temporarily disable the `x/group` . Since the x/group is be available in SDK v0.46 and later, we can use it again when the upgrade to 0.47.x is complete.

**Pull request closed without merging**
