### PR TITLE
Addressbook module

### PR DESCRIPTION
**Pull request by avalkov**

### CODE REVIEW

**Comment by mlukanova** [comment]
We would need queries by record creator. Also think about adding a functionality to delete all links by creator - this can be a transaction with multiple messages.
When creating a new address with ` cudos-noded tx addressbook create-address` if the label and network are found on chain but the address is different no indication of an already existing record is shown to the user. This may lead to confusion.

**Comment by avalkov** [comment]
> We would need queries by record creator. Also think about adding a functionality to delete all links by creator - this can be a transaction with multiple messages. When creating a new address with ` cudos-noded tx addressbook create-address` if the label and network are found on chain but the address is different no indication of an already existing record is shown to the user. This may lead to confusion.

I didnt added queries by creator and deletion of all links by creator because I don't see use case right now. But for future we could need them so I will add them. 
About the second thing, be no indication, if user X added address for network BTC and label 1@testdenom and then user Y wants to add address for the same network and same label, there should be no indications.

**Comment by Infra1515** [comment]
Just a general note about the code structure - I see that the client/tx.go and client/query.go are empty and the logic is outside. The same goes for keeper.go and grpc_query.go . In other modules from the cosmos-sdk ( example : https://github.com/cosmos/cosmos-sdk/tree/main/x/distribution/) and in our other modules the code is structured in different pattern - the logic is not separated in so many files and concentrated in keeper.go and grpc_query.go
Otherwise looks good.

**Comment by avalkov** [comment]
> Just a general note about the code structure - I see that the client/tx.go and client/query.go are empty and the logic is outside. The same goes for keeper.go and grpc_query.go . In other modules from the cosmos-sdk ( example : https://github.com/cosmos/cosmos-sdk/tree/main/x/distribution/) and in our other modules the code is structured in different pattern - the logic is not separated in so many files and concentrated in keeper.go and grpc_query.go Otherwise looks good.

Thats how it was scaffolded by latest version of ignite.

**Pull request merged**
