### PR TITLE
refactor: using apptesting to write unit test

### PR DESCRIPTION
**Pull request by dao-notional**
Refactor: refactoring test to use `apptesting` instead of `sim app`

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
@dao-notional can you pause working on this and move on to this item instead: https://github.com/CudoVentures/cudos-node/issues/98

**Comment by nghuyenthevinh2000** [comment]
@dao-notional, I hope you can recreate this pull request based on this branch instead: https://github.com/CudoVentures/cudos-node/pull/103

Thanks you!

**Comment by dao-notional** [comment]
sure @nghuyenthevinh2000 . I will recreate new PR from dev. And close this PR

**Comment by dao-notional** [comment]
Closed due to need rebase from dev branch

**Pull request closed without merging**
